//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSpawts.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentType()
        {
            this.Tournaments = new HashSet<Tournament>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.Guid FormatID { get; set; }
        public string Description { get; set; }
        public System.Guid GameID { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tournament> Tournaments { get; set; }
        public virtual TournamentFormat TournamentFormat { get; set; }
    }
}
