//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSpawts.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.TournamentUsers = new HashSet<TournamentUser>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid UserID { get; set; }
        public bool Retired { get; set; }
        public System.Guid TypeID { get; set; }
        public System.Guid GameID { get; set; }
        public string Slug { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentUser> TournamentUsers { get; set; }
        public virtual TournamentType TournamentType { get; set; }
        public virtual User User { get; set; }
    }
}
