//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSpawts.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentUser
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid TournamentID { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual User User { get; set; }
    }
}
